// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    Todo: typeof import('./src/components/Todo.vue')['default']
    TodoHeader: typeof import('./src/components/TodoHeader.vue')['default']
    TodoItem: typeof import('./src/components/TodoItem.vue')['default']
    TodoItemLabel: typeof import('./src/components/TodoItemLabel.vue')['default']
    TodoNewItem: typeof import('./src/components/TodoNewItem.vue')['default']
  }
}

export {}
